// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ProfileUser.Models;

namespace ProfileUser.Migrations
{
    [DbContext(typeof(ProfileContext))]
    partial class ProfileContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("ProfileUser.Models.Profile", b =>
                {
                    b.Property<int>("PID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("About")
                        .IsRequired()
                        .HasColumnType("varchar(500)");

                    b.Property<string>("CV")
                        .IsRequired()
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Contact")
                        .IsRequired()
                        .HasColumnType("varchar(12)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasColumnType("varchar(16)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(25)");

                    b.Property<string>("ProfilePic")
                        .IsRequired()
                        .HasColumnType("varchar(100)");

                    b.Property<string>("SurName")
                        .IsRequired()
                        .HasColumnType("nvarchar(25)");

                    b.Property<string>("Website")
                        .IsRequired()
                        .HasColumnType("varchar(500)");

                    b.HasKey("PID");

                    b.ToTable("Profiles");

                    b.HasData(
                        new
                        {
                            PID = 1,
                            About = "A mosotho young men who is inlove with software development",
                            CV = " ",
                            Contact = "57090909",
                            Email = "stseki@gmail.com",
                            Gender = "male",
                            Name = "Tsekiso",
                            ProfilePic = " ",
                            SurName = "Thokoana",
                            Website = "www.stseki.com"
                        },
                        new
                        {
                            PID = 2,
                            About = "A mosotho young men who is inlove with software development",
                            CV = " ",
                            Contact = "57133124",
                            Email = "stseki@gmail.com",
                            Gender = "male",
                            Name = "Setumo",
                            ProfilePic = " ",
                            SurName = "Semakela",
                            Website = "www.stseki.com"
                        },
                        new
                        {
                            PID = 3,
                            About = "A mosotho young men who is inlove with software development",
                            CV = " ",
                            Contact = "57133124",
                            Email = "stseki@gmail.com",
                            Gender = "male",
                            Name = "Thabo",
                            ProfilePic = " ",
                            SurName = "Majoro",
                            Website = "www.stseki.com"
                        },
                        new
                        {
                            PID = 4,
                            About = "A mosotho young men who is inlove with software development",
                            CV = " ",
                            Contact = "57133124",
                            Email = "stseki@gmail.com",
                            Gender = "male",
                            Name = "Khauta",
                            ProfilePic = " ",
                            SurName = "Maliehe",
                            Website = "www.stseki.com"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
